-- ChequeClaro — migración PostgreSQL/Supabase
-- Ejecutar el archivo completo desde Supabase > SQL Editor.
-- No elimina tablas ni datos existentes.
-- Las columnas usan snake_case porque coinciden con server/dbPostgres.ts.

CREATE TABLE IF NOT EXISTS public.cheques (
  id TEXT PRIMARY KEY,
  timestamp BIGINT NOT NULL,
  image_url TEXT NOT NULL DEFAULT '',
  cuit TEXT,
  cuit_validation TEXT NOT NULL DEFAULT 'UNKNOWN',
  cheque_numero TEXT,
  banco TEXT,
  importe NUMERIC(20, 2),
  moneda TEXT NOT NULL DEFAULT 'ARS',
  fecha_pago DATE,
  librador TEXT,
  ocr_text TEXT NOT NULL DEFAULT '',
  confidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  extraction_mode TEXT NOT NULL DEFAULT 'gemini_vision',
  edited_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
  bcra_result JSONB,
  quote_result JSONB,
  status TEXT NOT NULL DEFAULT 'confirmado',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cheques_cuit_validation_check
    CHECK (cuit_validation IN ('VALID', 'INVALID', 'UNKNOWN')),
  CONSTRAINT cheques_importe_nonnegative_check
    CHECK (importe IS NULL OR importe >= 0),
  CONSTRAINT cheques_moneda_not_blank_check
    CHECK (length(btrim(moneda)) > 0),
  CONSTRAINT cheques_status_not_blank_check
    CHECK (length(btrim(status)) > 0)
);

CREATE TABLE IF NOT EXISTS public.cheque_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cheque_id TEXT NOT NULL,
  field_name TEXT NOT NULL,
  original_value TEXT,
  corrected_value TEXT,
  timestamp BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cheque_corrections_cheque_fk
    FOREIGN KEY (cheque_id)
    REFERENCES public.cheques(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT cheque_corrections_field_name_check
    CHECK (field_name IN (
      'cuit',
      'chequeNumero',
      'banco',
      'importe',
      'fechaPago',
      'librador'
    ))
);

CREATE INDEX IF NOT EXISTS cheques_timestamp_idx
  ON public.cheques (timestamp DESC);

CREATE INDEX IF NOT EXISTS cheques_fecha_pago_idx
  ON public.cheques (fecha_pago);

CREATE INDEX IF NOT EXISTS cheques_status_idx
  ON public.cheques (status);

CREATE INDEX IF NOT EXISTS cheques_cuit_idx
  ON public.cheques (cuit);

CREATE INDEX IF NOT EXISTS cheques_cheque_numero_idx
  ON public.cheques (cheque_numero);

CREATE INDEX IF NOT EXISTS cheques_librador_idx
  ON public.cheques (librador);

CREATE INDEX IF NOT EXISTS cheque_corrections_cheque_id_idx
  ON public.cheque_corrections (cheque_id);

CREATE INDEX IF NOT EXISTS cheque_corrections_timestamp_idx
  ON public.cheque_corrections (timestamp DESC);

CREATE INDEX IF NOT EXISTS cheques_librador_lower_idx
  ON public.cheques (lower(librador));

-- Verificación opcional después de ejecutar:
-- SELECT table_schema, table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
--   AND table_name IN ('cheques', 'cheque_corrections')
-- ORDER BY table_name;
